TOTAL_SALES = "TOTAL_SALES"
PREVIOUS_YEAR_SALES = "PREVIOUS_YEAR_SALES"
SALES = "SALES"
GROSS_PROFIT = "GROSS_PROFIT"
NET_PROFIT = "NET_PROFIT"
EBIT = "EBIT"
EBITDA = "EBITDA"
GROSS_PROFIT_IN_3_YEARS = "GROSS_PROFIT_IN_3_YEARS"
PROFIT_ON_OPERATING_ACTIVITIES = "PROFIT_ON_OPERATING_ACTIVITIES"
PROFIT_ON_SALES = "PROFIT_ON_SALES"
TOTAL_COSTS = "TOTAL_COSTS"
COST_OF_PRODUCTS_SOLD = "COST_OF_PRODUCTS_SOLD"
OPERATING_EXPENSES = "OPERATING_EXPENSES"
DEPRECIATION = "DEPRECIATION"
INTEREST = "INTEREST"
FINANCIAL_EXPENSES = "FINANCIAL_EXPENSES"
EXTRAORDINARY_ITEMS = "EXTRAORDINARY_ITEMS"

INCOME_STATEMENT = [
    TOTAL_SALES,
    PREVIOUS_YEAR_SALES,
    SALES,
    GROSS_PROFIT,
    NET_PROFIT,
    EBIT,
    EBITDA,
    GROSS_PROFIT_IN_3_YEARS,
    PROFIT_ON_OPERATING_ACTIVITIES,
    PROFIT_ON_SALES,
    TOTAL_COSTS,
    COST_OF_PRODUCTS_SOLD,
    OPERATING_EXPENSES,
    DEPRECIATION,
    INTEREST,
    FINANCIAL_EXPENSES,
    EXTRAORDINARY_ITEMS,
]

TOTAL_ASSETS = "TOTAL_ASSETS"
FIXED_ASSETS = "FIXED_ASSETS"
CURRENT_ASSETS = "CURRENT_ASSETS"
INVENTORY = "INVENTORY"
RECEIVABLES = "RECEIVABLES"
SHORT_TERM_SECURITIES = "SHORT_TERM_SECURITIES"
CASH = "CASH"
TOTAL_LIABILITIES = "TOTAL_LIABILITIES"
SHORT_TERM_LIABILITIES = "SHORT_TERM_LIABILITIES"
WORKING_CAPITAL = "WORKING_CAPITAL"
EQUITY = "EQUITY"
BOOK_VALUE_OF_EQUITY = "BOOK_VALUE_OF_EQUITY"
CONSTANT_CAPITAL = "CONSTANT_CAPITAL"
RETAINED_EARNINGS = "RETAINED_EARNINGS"
SHARE_CAPITAL = "SHARE_CAPITAL"

BANKRUPTCY_LABEL = "BANKRUPTCY_LABEL"

BALANCE_SHEET = [
    TOTAL_ASSETS,
    FIXED_ASSETS,
    CURRENT_ASSETS,
    INVENTORY,
    RECEIVABLES,
    SHORT_TERM_SECURITIES,
    CASH,
    TOTAL_LIABILITIES,
    SHORT_TERM_LIABILITIES,
    WORKING_CAPITAL,
    EQUITY,
    BOOK_VALUE_OF_EQUITY,
    CONSTANT_CAPITAL,
    RETAINED_EARNINGS,
    SHARE_CAPITAL,
]

assert len(INCOME_STATEMENT) == 17
assert len(BALANCE_SHEET) == 15
